# Generated by Django 3.0.5 on 2020-09-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'SAVINGS'), ('CURRENT', 'CURRENT'), ('LOAN', 'LOAN'), ('LENDING', 'LENDING')], default='CURRENT', max_length=32),
        ),
    ]
