# Generated by Django 3.0.5 on 2020-09-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200905_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
