# Generated by Django 3.0.5 on 2020-09-05 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='accounts.Commitment'),
        ),
    ]
